#!/usr/bin/env python

"""
    Copyright (C) 2014 Foxel http://www.foxel.ch
    Author: Kevin Velickovic

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import os

__HOME_FOLDER__ = os.path.expanduser("~")
__SSH_KEY_FILE__ = "%s/.ssh/id_rsa.pub" % __HOME_FOLDER__
__SSH_HOSTS_FILE__ = "%s/.parallel/sshloginfile" % __HOME_FOLDER__

if not os.path.isfile(__SSH_KEY_FILE__):
    print "SSH public key not found, creating one"
    os.system("ssh-keygen -t rsa")

if os.path.isfile(__SSH_HOSTS_FILE__):
    SSH_FILE = open(__SSH_HOSTS_FILE__, 'r')
    SSH_FILE_CONTENT = SSH_FILE.read().rstrip()
    SSH_HOSTS = SSH_FILE_CONTENT.split(',')

    for Host in SSH_HOSTS:
        os.system('ssh-copy-id %s' % Host)

    SSH_FILE.close()
else:
    print "No parallel sshloginfile file found"
